"""accounts table

Revision ID: 3a4055d3f1e0
Revises: 7af21a22f0d1
Create Date: 2018-10-31 14:01:50.498450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4055d3f1e0'
down_revision = '7af21a22f0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_host', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_host')
    # ### end Alembic commands ###
